-- Migration 009: project files, contact preferences, manual quote source, custom project types

-- ── project_files ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS project_files (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  mime_type text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE project_files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "project_files_all" ON project_files FOR ALL USING (true) WITH CHECK (true);

-- ── contact_preferences on customers ──────────────────────────────────────
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_preferences jsonb DEFAULT '{}'::jsonb;

-- ── source on quotes ──────────────────────────────────────────────────────
-- Tracks whether quote was generated by AI or created manually
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS source text DEFAULT 'ai';

-- ── custom_project_types ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS custom_project_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  key text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE custom_project_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "custom_project_types_all" ON custom_project_types FOR ALL USING (true) WITH CHECK (true);
